apiVersion: v1
kind: Service
metadata:
  name: gc-inventory-svc
  namespace: greencompute
  labels:
    app: browncompute-dal
spec:
  type: NodePort
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
      name: http
  selector:
    app: browncompute-dal
