# This dockerfile assume the build is done before
FROM websphere-liberty:webProfile7
MAINTAINER https://github.com/ibm-cloud-architecture - IBM - Jerome Boyer - Fabio Gomez
RUN installUtility install --acceptLicense jpa-2.0 jaxws-2.2 adminCenter-1.0

# Copy Code Over
RUN mkdir /dalapp
WORKDIR /dalapp
COPY . /dalapp

# Create Directory
RUN mkdir /opt/ibm/wlp/usr/shared/config/lib

# Add jar and war files
COPY  src/main/liberty/config/server.xml /opt/ibm/wlp/usr/servers/defaultServer/server.xml
COPY lib/db2jcc4.jar /opt/ibm/wlp/usr/shared/config/lib
COPY  build/libs/refarch-integration-inventory-dal.war /opt/ibm/wlp/usr/servers/defaultServer/apps

# Set Port
EXPOSE 9080 9443

# Start
ENTRYPOINT ["/opt/ibm/wlp/bin/server", "run", "defaultServer"]
