apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name  }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  - port: {{ .Values.service.externalSPort }}
    targetPort: {{ .Values.service.internalSPort }}
    protocol: TCP
    name: https
  selector:
    app: {{ template "fullname" . }}
